// Export pages
export '/home_page/home_page_widget.dart' show HomePageWidget;
export '/shopping/shopping_widget.dart' show ShoppingWidget;
export '/analyze/analyze_widget.dart' show AnalyzeWidget;
export '/sport/sport_widget.dart' show SportWidget;
export '/social/social_widget.dart' show SocialWidget;
export '/diet_plan/diet_plan_widget.dart' show DietPlanWidget;
export '/sign_in/sign_in_widget.dart' show SignInWidget;
export '/user/user_widget.dart' show UserWidget;
export '/send_forget_val/send_forget_val_widget.dart' show SendForgetValWidget;
export '/timer/timer_widget.dart' show TimerWidget;
export '/food/food_widget.dart' show FoodWidget;
export '/record/record_widget.dart' show RecordWidget;
export '/nutrient/nutrient_widget.dart' show NutrientWidget;
export '/view_food/view_food_widget.dart' show ViewFoodWidget;
export '/target_setting1/target_setting1_widget.dart' show TargetSetting1Widget;
export '/food_recommand/food_recommand_widget.dart' show FoodRecommandWidget;
export '/target_setting2/target_setting2_widget.dart' show TargetSetting2Widget;
export '/target_setting3/target_setting3_widget.dart' show TargetSetting3Widget;
export '/setting/setting_widget.dart' show SettingWidget;
export '/user_setting/user_setting_widget.dart' show UserSettingWidget;
export '/classify_food/classify_food_widget.dart' show ClassifyFoodWidget;
export '/select_analyze/select_analyze_widget.dart' show SelectAnalyzeWidget;
export '/nutrient_record/nutrient_record_widget.dart' show NutrientRecordWidget;
export '/weight_analyze/weight_analyze_widget.dart' show WeightAnalyzeWidget;
export '/sport_record/sport_record_widget.dart' show SportRecordWidget;
export '/sport_ball/sport_ball_widget.dart' show SportBallWidget;
export '/sport_swim/sport_swim_widget.dart' show SportSwimWidget;
export '/sport_run/sport_run_widget.dart' show SportRunWidget;
export '/sport_yoga/sport_yoga_widget.dart' show SportYogaWidget;
export '/product/product_widget.dart' show ProductWidget;
export '/record_water/record_water_widget.dart' show RecordWaterWidget;
export '/view_food2/view_food2_widget.dart' show ViewFood2Widget;
export '/view_food3/view_food3_widget.dart' show ViewFood3Widget;
export '/view_food4/view_food4_widget.dart' show ViewFood4Widget;
export '/water_target/water_target_widget.dart' show WaterTargetWidget;
export '/view_sport/view_sport_widget.dart' show ViewSportWidget;
export '/food_weekend/food_weekend_widget.dart' show FoodWeekendWidget;
export '/sport_bike/sport_bike_widget.dart' show SportBikeWidget;
export '/sport_other/sport_other_widget.dart' show SportOtherWidget;
export '/sport_costumize/sport_costumize_widget.dart' show SportCostumizeWidget;
export '/details04_coffee_product/details04_coffee_product_widget.dart'
    show Details04CoffeeProductWidget;
export '/search_page/search_page_widget.dart' show SearchPageWidget;
export '/food_costumize/food_costumize_widget.dart' show FoodCostumizeWidget;
export '/food_costumize_copy/food_costumize_copy_widget.dart'
    show FoodCostumizeCopyWidget;
export '/photo_response/photo_response_widget.dart' show PhotoResponseWidget;
export '/success_page/success_page_widget.dart' show SuccessPageWidget;
export '/tmpp/tmpp_widget.dart' show TmppWidget;
export '/password_val/password_val_widget.dart' show PasswordValWidget;
